### PR TITLE
test: added end-to-end style unit test

### LINKED ISSUE #176: 🛠 Tooling: Increase text coverage to a not-red indicator
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/all-contributors-auto-action/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Right now, codecov indicates test coverage for this repo is 29%. That shows up with an orange background in the README.md badge, on its scale from red to orange to yellow to green. Not an ideal look for the repository.

### Additional Info

Having badges angrily proclaim low test coverage numbers is part of why I like having them in the README.md 😄. It's good encouragement to raise test coverage!

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
## PR Checklist

- [x] Addresses an existing open issue: fixes #176
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/all-contributors-auto-action/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/all-contributors-auto-action/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

Adds a "unit" test that acts more as an end-to-end test. It mocks out the GitHub APIs and `all-contributors-for-repository`, then async imports `./index.js`.

Raises line coverage to near-100%, though it does miss a few lines. I don't feel motivated to really dive in and get true 100% coverage myself. That's fine as followup good first issues if anybody wants to ramp up on contributing.

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -85,7 +85,5 @@ for (const [contributor, contributions] of Object.entries(contributors)) {
 			const newComment = await octokit.request(...commentRequestArgs);
 			core.debug(`Posted comment ${newComment.data.id} for ${latestId}.`);
 		}
-
-		console.log("POST /repos/{owner}/{repo}/issues/{issue_number}/comments");
```
Comment (JoshuaKGoldberg) [inline src/index.ts:89]: Tangentially: this was newly being caught by unit tests. The log is unnecessary anyway.
